{{- if .Values.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/component: controller
  name: {{ .Values.controller.ingressClass.name }}
  {{- if .Values.controller.ingressClass.setAsDefaultClass }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  {{- end }}
spec:
  controller: {{ .Values.controller.ingressClass.controller }}
{{- end }}