# Echo MCP Service Example
# HTTP-based MCP service demonstrating direct container deployment
#
# IMPORTANT: Update the namespace and workspace ID to match your workspace:
# - namespace: Set to your workspace namespace (e.g., ws-myworkspace-uuid)
# - mcp.nimbletools.dev/workspace: Set to your workspace UUID
#
# Usage:
#   1. Update namespace and workspace ID below
#   2. kubectl apply -f echo-mcp.yaml
#   3. kubectl get mcpservices
#   4. kubectl logs -l app=echo

apiVersion: mcp.nimbletools.dev/v1
kind: MCPService
metadata:
  name: echo
  namespace: YOUR_WORKSPACE_ID # UPDATE THIS: Use your workspace namespace (ws-name-uuid)
  labels:
    mcp.nimbletools.dev/service: "true"
    mcp.nimbletools.dev/workspace: "YOUR_WORKSPACE_ID" # UPDATE THIS: Your workspace UUID
  annotations:
    mcp.nimbletools.dev/description: "Echo MCP service for testing"
    mcp.nimbletools.dev/version: "1.0.0"
spec:
  # Basic configuration
  replicas: 1
  timeout: 300
  environment:
    LOG_LEVEL: "info"

  # Container configuration - direct HTTP MCP server
  container:
    image: "nimbletools/mcp-echo:latest"
    registry: "docker.io"
    port: 8000

  # HTTP deployment (no universal adapter needed)
  deployment:
    type: "http"
    healthPath: "/health"

  credentials: []

  # Resource limits
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  # Auto-scaling configuration
  scaling:
    minReplicas: 0
    maxReplicas: 10
    targetConcurrency: 10
    scaleDownDelay: "5m"

  # Routing configuration
  routing:
    path: "/services/echo"
    port: 8000
    healthPath: "/health"
    discoveryPath: "/mcp/discover"
