apiVersion: v2
name: nginx-ingress
description: NGINX Ingress Controller for Kubernetes
type: application
version: 0.1.0
appVersion: "1.10.1"
keywords:
  - ingress
  - nginx
maintainers:
  - name: NimbleTools Team
home: https://github.com/kubernetes/ingress-nginx